name: syntax 8.3
on:
  pull_request:
    branches:
      - master
jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Run pint
        run: php vendor/bin/pint --test

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Chckout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2, phpstan
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Run phpstan
        run: vendor/bin/phpstan analyse  -c phpstan.dist.neon src

